### ISSUE TITLE
test_model: modelのテストをシンプルにできるようにする

### ISSUE THREAD

**Issue by koike-ya** [Tomoya-K-0504/eeglibrary#2]
test_manifest.csvを読み込んで予想すればよい。
inferは関数として別に作り、ラベルがあるテストとないテストを分けること。

**Comment by Tomoya-K-0504** [comment]
https://github.com/Tomoya-K-0504/epilepsy/pull/3

**Comment by koike-ya** [comment]
seizure-predictionのようにinferenceしたいときはあるはずで、今はinferenceのコードもライブラリの中に入ってしまっているので、外に出す。

**Comment by koike-ya** [comment]
https://github.com/Tomoya-K-0504/eeglibrary/pull/3
